[package]
name = "llhd-est"
version = "0.1.0"
authors = ["Fabian Schuiki <fabian@schuiki.ch>"]
edition = "2018"

[dependencies]
llhd = { git = "https://github.com/fabianschuiki/llhd", rev = "ccc27e4" }
clap = "2"
bincode = "1.2"
